# Generated by Django 4.0.3 on 2022-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('sigla', models.CharField(max_length=30, verbose_name='sigla')),
                ('setor', models.CharField(max_length=30, verbose_name='setor')),
            ],
        ),
    ]
